apiVersion: apps/v1
kind: Deployment
metadata:
  name: oi-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oi-app
  template:
    metadata:
      labels:
        app: oi-app
    spec:
      containers:
        - name: OI_app
          image: asnaidu1/oi-sprint
          ports:
            - containerPort: 8089
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://ash-sprint-rds.cmdlxfdnrfju.ap-south-1.rds.amazonaws.com:3306/AshDatabase
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mysql-secrets
                  key: MYSQL_USER
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secrets
                  key: MYSQL_PASSWORD
